"
"     ██▒   █▓ ██▓ ███▄ ▄███▓ ██▀███   ▄████▄
"    ▓██░   █▒▓██▒▓██▒▀█▀ ██▒▓██ ▒ ██▒▒██▀ ▀█
"     ▓██  █▒░▒██▒▓██    ▓██░▓██ ░▄█ ▒▒▓█    ▄
"      ▒██ █░░░██░▒██    ▒██ ▒██▀▀█▄  ▒▓▓▄ ▄██▒
"       ▒▀█░  ░██░▒██▒   ░██▒░██▓ ▒██▒▒ ▓███▀ ░
"       ░ ▐░  ░▓  ░ ▒░   ░  ░░ ▒▓ ░▒▓░░ ░▒ ▒  ░
"       ░ ░░   ▒ ░░  ░      ░  ░▒ ░ ▒░  ░  ▒
"         ░░   ▒ ░░      ░     ░░   ░ ░
"          ░   ░         ░      ░     ░ ░
"         ░                           ░

set number "This turns on line numbers
set noswapfile "Disable annoying swap files

" set paste "Turn on paste mode

"Turn on Syntax
syntax on
set re=0

set rnu

"Function Hotkeys
:map <F2> :setlocal spell! spelllang=en_us<CR>
map <F3> :s/foo/bar/g
map <F5> :!make<cr>
map <F6> :!make flash<cr>

"Tell vim not to jump over lines (: and ! makes it work in insert mode)
nmap <silent> <Down> gj
nmap <silent> <Up> gk

nmap <silent> j gj
nmap <silent> k gk

set ai " Auto indent
" set si " Smart indent
set nowrap " Wrap lines
set linebreak " Don't wrap words
set breakindent " Tab Wrapped lines

" Line Wrap
set whichwrap+=<,>,h,l,[,]

" Detect indentation automatically
filetype plugin indent on
set autoindent
set smarttab

" Follow existing file indentation
autocmd BufReadPost * if search('^\t', 'nw') | set noexpandtab | else | set expandtab | endif

" Default tab settings (adjust numbers if you like)
set tabstop=4
set shiftwidth=4
set softtabstop=4

set textwidth=0  " Disable hard wrapping; use gq with tw=80 manually

" Show the filename
set laststatus=2

set clipboard=unnamedplus
set hlsearch

autocmd VimResized * wincmd =

autocmd BufWritePre * %s/\s\+$//e

highlight Search ctermbg=yellow ctermfg=black guibg=yellow guifg=black

if has("cscope")
    cs add cscope.out
endif

" Load all packages in pack/*/start
if has('vim_starting')
    packloadall
endif

let g:fzf_history_dir = '~/.local/share/fzf-history'

" Highlight fenced code blocks in Markdown
let g:markdown_fenced_languages = [
      \ 'bash=sh',
      \ 'python',
      \ 'json',
      \ 'yaml',
      \ 'cpp',
      \ 'c'
      \ ]

tnoremap <C-w>h <C-\><C-n><C-w>h
tnoremap <C-w>j <C-\><C-n><C-w>j
tnoremap <C-w>k <C-\><C-n><C-w>k
tnoremap <C-w>l <C-\><C-n><C-w>l
