"
"     ██▒   █▓ ██▓ ███▄ ▄███▓ ██▀███   ▄████▄
"    ▓██░   █▒▓██▒▓██▒▀█▀ ██▒▓██ ▒ ██▒▒██▀ ▀█
"     ▓██  █▒░▒██▒▓██    ▓██░▓██ ░▄█ ▒▒▓█    ▄
"      ▒██ █░░░██░▒██    ▒██ ▒██▀▀█▄  ▒▓▓▄ ▄██▒
"       ▒▀█░  ░██░▒██▒   ░██▒░██▓ ▒██▒▒ ▓███▀ ░
"       ░ ▐░  ░▓  ░ ▒░   ░  ░░ ▒▓ ░▒▓░░ ░▒ ▒  ░
"       ░ ░░   ▒ ░░  ░      ░  ░▒ ░ ▒░  ░  ▒
"         ░░   ▒ ░░      ░     ░░   ░ ░
"          ░   ░         ░      ░     ░ ░
"         ░                           ░

set number "This turns on line numbers
set noswapfile "Disable annoying swap files

set paste "Turn on paste mode

"Turn on Syntax
syntax on
set re=0

set rnu

"Function Hotkeys
:map <F2> :setlocal spell! spelllang=en_us<CR>
map <F3> :s/foo/bar/g
map <F5> :!make<cr>
map <F6> :!make flash<cr>

"Tell vim not to jump over lines (: and ! makes it work in insert mode)
nmap <silent> <Down> gj
nmap <silent> <Up> gk

nmap <silent> j gj
nmap <silent> k gk

set ai " Auto indent
" set si " Smart indent
set wrap " Wrap lines
set linebreak " Don't wrap words
set breakindent " Tab Wrapped lines

" Line Wrap
set whichwrap+=<,>,h,l,[,]

" Detect indentation automatically
filetype plugin indent on
set autoindent
set smarttab

" Follow existing file indentation
autocmd BufReadPost * if search('^\t', 'nw') | set noexpandtab | else | set expandtab | endif

" Default tab settings (adjust numbers if you like)
set tabstop=4
set shiftwidth=4
set softtabstop=4

set textwidth=80 " Set text to wrap. To format text use the :gq

" Show the filename
set laststatus=2

set clipboard=unnamedplus
set hlsearch

autocmd VimResized * wincmd =

nnoremap H <C-w>h
nnoremap J <C-w>j
nnoremap K <C-w>k
nnoremap L <C-w>l

autocmd BufWritePre * %s/\s\+$//e

highlight Search ctermbg=yellow ctermfg=black guibg=yellow guifg=black

nnoremap * *``
nnoremap * :keepjumps normal! mi*`i<CR>
nnoremap <C-]> :sp<CR>:tag <C-R><C-W><CR>

set cscopequickfix=s-,c-,d-,i-,t-,e-
if has("cscope")
    cs add cscope.out
endif

" Load all packages in pack/*/start
if has('vim_starting')
    packloadall
endif

" Packages
" cd ~/.vim
" mkdir -p pack/plugins/start
" cd pack/plugins/start
" git clone https://github.com/tpope/vim-fugitive.git
